# Generated by Django 6.0.7 on 2026-08-05 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature_request', 'Feature Request'), ('data_issue', 'Data Issue'), ('prediction_issue', 'Prediction Issue'), ('portfolio_issue', 'Portfolio Issue'), ('ui_issue', 'User Interface Issue'), ('performance_issue', 'Performance Issue'), ('account_issue', 'Account Issue'), ('other', 'Other')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(max_length=5000)),
                ('reporter_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('admin_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('resolved', 'Resolved'), ('duplicate', 'Duplicate'), ('cannot_reproduce', 'Cannot Reproduce'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='new', max_length=20)),
                ('page_path', models.CharField(blank=True, max_length=255)),
                ('steps_to_reproduce', models.TextField(blank=True, max_length=3000)),
                ('expected_behavior', models.TextField(blank=True, max_length=2000)),
                ('actual_behavior', models.TextField(blank=True, max_length=2000)),
                ('admin_response', models.TextField(blank=True, max_length=3000)),
                ('internal_notes', models.TextField(blank=True)),
                ('contact_allowed', models.BooleanField(default=True)),
                ('meta_exchange', models.CharField(blank=True, max_length=3)),
                ('meta_trading_code', models.CharField(blank=True, max_length=32)),
                ('meta_analysis_date', models.DateField(blank=True, null=True)),
                ('meta_model_version', models.CharField(blank=True, max_length=32)),
                ('meta_quote_timestamp', models.DateTimeField(blank=True, null=True)),
                ('meta_data_source', models.CharField(blank=True, max_length=64)),
                ('meta_prediction_reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_assigned', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='feedback.feedback')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('priority_set', 'Priority set'), ('assigned', 'Assigned'), ('note_added', 'Internal note added'), ('response_posted', 'Response posted'), ('reporter_follow_up', 'Reporter follow-up'), ('reporter_disputed_resolution', 'Reporter marked still unresolved'), ('marked_duplicate', 'Marked duplicate')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='feedback.feedback')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status', '-created_at'], name='feedback_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['category', '-created_at'], name='feedback_category_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['reporter', '-created_at'], name='feedback_reporter_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['admin_priority', '-created_at'], name='feedback_adminprio_created_idx'),
        ),
    ]
