# Generated by Django 6.0.7 on 2026-07-27 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('strategy', models.CharField(max_length=64)),
                ('exchange', models.CharField(blank=True, choices=[('DSE', 'Dhaka Stock Exchange'), ('CSE', 'Chittagong Stock Exchange')], max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('avg_return_pct', models.FloatField(default=0)),
                ('avg_days_to_peak', models.FloatField(blank=True, null=True)),
                ('avg_days_to_target', models.FloatField(blank=True, null=True)),
                ('max_drawdown_pct', models.FloatField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('DSE', 'Dhaka Stock Exchange'), ('CSE', 'Chittagong Stock Exchange')], max_length=3)),
                ('as_of', models.DateField()),
                ('index_value', models.FloatField(blank=True, null=True)),
                ('index_change_pct', models.FloatField(blank=True, null=True)),
                ('total_volume', models.BigIntegerField(blank=True, null=True)),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('advancers', models.IntegerField(default=0)),
                ('decliners', models.IntegerField(default=0)),
                ('unchanged', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-as_of'],
                'unique_together': {('exchange', 'as_of')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('DSE', 'Dhaka Stock Exchange'), ('CSE', 'Chittagong Stock Exchange')], default='DSE', max_length=3)),
                ('trading_code', models.CharField(db_index=True, max_length=32)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=128)),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('G', 'G'), ('N', 'N'), ('Z', 'Z'), ('U', 'Unknown')], default='U', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('last_change_pct', models.FloatField(blank=True, null=True)),
                ('last_volume', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['trading_code'],
                'unique_together': {('exchange', 'trading_code')},
            },
        ),
        migrations.CreateModel(
            name='PatternHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('direction', models.CharField(max_length=8)),
                ('strength', models.FloatField(default=0.5)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='market.stock')),
            ],
            options={
                'ordering': ['-as_of', '-strength'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.stock')),
            ],
            options={
                'verbose_name_plural': 'price histories',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', '-date'], name='market_pric_stock_i_432cb3_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True)),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('HOLD', 'Hold'), ('SELL', 'Sell'), ('WATCH', 'Watch')], default='HOLD', max_length=8)),
                ('score', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='medium', max_length=16)),
                ('is_safe_buy', models.BooleanField(default=False)),
                ('maturity_days_est', models.IntegerField(blank=True, null=True)),
                ('peak_days_est', models.IntegerField(blank=True, null=True)),
                ('expected_return_pct', models.FloatField(blank=True, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('ml_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='market.stock')),
            ],
            options={
                'ordering': ['-score', '-confidence'],
                'unique_together': {('stock', 'as_of')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True)),
                ('sma_20', models.FloatField(blank=True, null=True)),
                ('sma_50', models.FloatField(blank=True, null=True)),
                ('sma_200', models.FloatField(blank=True, null=True)),
                ('ema_12', models.FloatField(blank=True, null=True)),
                ('ema_26', models.FloatField(blank=True, null=True)),
                ('rsi_14', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('macd_signal', models.FloatField(blank=True, null=True)),
                ('macd_hist', models.FloatField(blank=True, null=True)),
                ('bb_upper', models.FloatField(blank=True, null=True)),
                ('bb_middle', models.FloatField(blank=True, null=True)),
                ('bb_lower', models.FloatField(blank=True, null=True)),
                ('atr_14', models.FloatField(blank=True, null=True)),
                ('volume_sma_20', models.FloatField(blank=True, null=True)),
                ('support', models.FloatField(blank=True, null=True)),
                ('resistance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicals', to='market.stock')),
            ],
            options={
                'ordering': ['-as_of'],
                'unique_together': {('stock', 'as_of')},
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stocks', models.ManyToManyField(blank=True, related_name='watchlists', to='market.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
