# Generated by Django 6.0.7 on 2026-07-28 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseLearnState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='global', max_length=32, unique=True)),
                ('return_bias', models.FloatField(default=0.0, help_text='EMA of (predicted_return − actual_return); subtracted from future forecasts')),
                ('mae', models.FloatField(default=0.0, help_text='Mean absolute price error on settled forecasts')),
                ('mape', models.FloatField(default=0.0, help_text='Mean abs % error')),
                ('direction_hit_rate', models.FloatField(default=0.0)),
                ('settled_count', models.IntegerField(default=0)),
                ('last_forecast_at', models.DateTimeField(blank=True, null=True)),
                ('last_settled_at', models.DateTimeField(blank=True, null=True)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NextDayCloseForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True, help_text='Session date when the forecast was made (after close)')),
                ('target_date', models.DateField(db_index=True, help_text='Next trading day being forecast')),
                ('last_close', models.FloatField()),
                ('predicted_close', models.FloatField()),
                ('predicted_return', models.FloatField(help_text='Predicted close/close−1 return')),
                ('confidence', models.FloatField(default=0.5)),
                ('method', models.CharField(default='analogue+bias', max_length=32)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('actual_close', models.FloatField(blank=True, null=True)),
                ('abs_error', models.FloatField(blank=True, null=True)),
                ('pct_error', models.FloatField(blank=True, null=True)),
                ('return_error', models.FloatField(blank=True, help_text='predicted_return − actual_return', null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_forecasts', to='market.stock')),
            ],
            options={
                'ordering': ['-target_date', '-as_of'],
                'indexes': [models.Index(fields=['settled_at'], name='market_next_settled_c4c477_idx'), models.Index(fields=['as_of'], name='market_next_as_of_fd8627_idx')],
                'unique_together': {('stock', 'target_date')},
            },
        ),
    ]
