# Generated by Django 6.0.7 on 2026-07-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_taskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text='e.g. forward_return_rf, next_close_rf', max_length=64)),
                ('version', models.CharField(help_text='Timestamp-based, e.g. 20260729-101530', max_length=32)),
                ('exchange_scope', models.CharField(default='combined', help_text='DSE / CSE / combined', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('experimental', 'Experimental'), ('inactive', 'Inactive')], default='experimental', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('data_cutoff', models.DateField(help_text='Latest price bar date included in training data')),
                ('feature_schema', models.JSONField(blank=True, default=list)),
                ('train_rows', models.IntegerField(default=0)),
                ('fold_metadata', models.JSONField(blank=True, default=list, help_text='Per-fold dates, sample counts, class balance')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Aggregated walk-forward metrics incl. baseline comparisons')),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('backup_path', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
    ]
