# Generated by Django 6.0.7 on 2026-07-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_mlmodelversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='annualized_return_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='avg_exposure_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='avg_loss_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='avg_win_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='benchmark_buy_hold_return_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='benchmark_index_return_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Results by year / exchange / sector, with min-sample warnings'),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='cost_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='data_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='data_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='engine_version',
            field=models.CharField(default='v1', help_text='v1 = pre-Phase-5 single-stock engine (legacy rows, kept for history). v2 = portfolio engine with costs/liquidity/benchmarks.', max_length=8),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='final_cash',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='final_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='initial_cash',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='profit_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='sharpe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='sortino_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='total_costs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='total_return_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='turnover_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='warnings',
            field=models.JSONField(blank=True, default=list, help_text='Suspended securities, corporate-action exclusions, rejected/sized-down trades, etc.'),
        ),
    ]
