# Generated by Django 6.0.7 on 2026-07-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_backtestrun_annualized_return_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('unknown', 'Unknown (legacy / unspecified)'), ('dse_live', 'DSE live quote'), ('dse_history', 'DSE historical archive/bdshare'), ('cse_live', 'CSE live quote'), ('cse_history', 'CSE historical bulk download'), ('cse_mirror_fallback', 'CSE mirrored from DSE (not real CSE data)'), ('synthetic_demo', 'Synthetic demo seed data'), ('synthetic_fallback', 'Synthetic fallback for a real code (fetch unavailable)')], db_index=True, default='unknown', max_length=32)),
                ('exchange', models.CharField(blank=True, choices=[('DSE', 'Dhaka Stock Exchange'), ('CSE', 'Chittagong Stock Exchange')], max_length=3)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('stock_count', models.IntegerField(default=0)),
                ('request_meta', models.JSONField(blank=True, default=dict, help_text='URL/sub-source/status/counts/timing only — never headers, cookies or tokens')),
                ('error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='adjustment_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('raw', 'Raw / as-received (no corporate-action adjustment applied)'), ('adjusted', 'Adjusted for corporate actions')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='fetched_at',
            field=models.DateTimeField(blank=True, help_text='When this row was actually written by a fetch/seed; null for legacy rows where this was never recorded', null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='is_synthetic',
            field=models.BooleanField(db_index=True, default=False, help_text='True for demo-seeded/mirror-fallback data — excluded from live analysis by default'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='quality_flags',
            field=models.JSONField(blank=True, default=list, help_text='Detected issues: impossible OHLC, abnormal jump, stale-quote run, missing-session gap, etc.'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='source',
            field=models.CharField(choices=[('unknown', 'Unknown (legacy / unspecified)'), ('dse_live', 'DSE live quote'), ('dse_history', 'DSE historical archive/bdshare'), ('cse_live', 'CSE live quote'), ('cse_history', 'CSE historical bulk download'), ('cse_mirror_fallback', 'CSE mirrored from DSE (not real CSE data)'), ('synthetic_demo', 'Synthetic demo seed data'), ('synthetic_fallback', 'Synthetic fallback for a real code (fetch unavailable)')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_rows', to='market.importbatch'),
        ),
        migrations.CreateModel(
            name='PriceHistoryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('previous_open', models.FloatField(blank=True, null=True)),
                ('previous_high', models.FloatField(blank=True, null=True)),
                ('previous_low', models.FloatField(blank=True, null=True)),
                ('previous_close', models.FloatField(blank=True, null=True)),
                ('previous_volume', models.BigIntegerField(blank=True, null=True)),
                ('previous_source', models.CharField(blank=True, max_length=32)),
                ('new_source', models.CharField(blank=True, max_length=32)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('price_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='market.pricehistory')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_revisions', to='market.stock')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
