# Generated by Django 6.0.7 on 2026-08-01 14:52
#
# Seeds the initial DSE/CSE holiday list covering the ~1-year lookback
# window the stock-detail history table can show (see
# market/views.py::_history_rows_for_stock and HISTORY_RANGES). Sourced
# from public DSE holiday-notice reporting (calendarlabs.com's DSE 2025/2026
# holiday listings, cross-checked against news coverage for the Aug 5
# "July Uprising/Mass Uprising Day" national holiday). Dates that already
# fall on the regular Fri/Sat weekend are omitted — trading_calendar.py's
# is_weekend() already covers those. This is a one-time seed; going forward,
# holidays are added by hand via /admin (see market/admin.py::MarketHolidayAdmin)
# since DSE has no machine-readable holiday feed to sync from.
from django.db import migrations

HOLIDAYS = [
    ("2025-08-05", "July Mass Uprising Day"),
    ("2025-10-01", "Vijaya Dashami"),
    ("2025-12-25", "Christmas"),
    ("2026-02-04", "Shab-e-Barat"),
    ("2026-03-17", "Laylat al-Qadr"),
    ("2026-03-19", "Eid-ul-Fitr"),
    ("2026-03-22", "Eid-ul-Fitr"),
    ("2026-03-23", "Eid-ul-Fitr"),
    ("2026-03-26", "Independence Day"),
    ("2026-04-14", "Bengali New Year"),
    ("2026-05-26", "Eid-ul-Adha"),
    ("2026-05-27", "Eid-ul-Adha"),
    ("2026-05-28", "Eid-ul-Adha"),
    ("2026-07-01", "Bank Holiday"),
    ("2026-08-05", "July Uprising Day"),
    ("2026-08-26", "Mawlid"),
    ("2026-10-20", "Durga Puja Holiday"),
    ("2026-10-21", "Vijaya Dashami"),
    ("2026-12-16", "National Day"),
    ("2026-12-31", "Bank Holiday"),
]


def seed_holidays(apps, schema_editor):
    MarketHoliday = apps.get_model("market", "MarketHoliday")
    for date_str, name in HOLIDAYS:
        MarketHoliday.objects.get_or_create(date=date_str, defaults={"name": name})


def remove_seeded_holidays(apps, schema_editor):
    MarketHoliday = apps.get_model("market", "MarketHoliday")
    MarketHoliday.objects.filter(date__in=[d for d, _ in HOLIDAYS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_marketholiday"),
    ]

    operations = [
        migrations.RunPython(seed_holidays, remove_seeded_holidays),
    ]
