# Generated by Django 6.0.7 on 2026-08-01 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_seed_market_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_family', models.CharField(choices=[('forward_return_rf', 'Forward Return Classifier'), ('next_close_rf', 'Next Close Regressor')], db_index=True, max_length=32)),
                ('model_version_tag', models.CharField(help_text='Immutable copy of MLModelVersion.version at capture time', max_length=32)),
                ('feature_schema_version', models.CharField(blank=True, help_text='Hash of the feature-column list used at capture time', max_length=32)),
                ('exchange', models.CharField(choices=[('DSE', 'Dhaka Stock Exchange'), ('CSE', 'Chittagong Stock Exchange')], db_index=True, max_length=3)),
                ('stock_trading_code', models.CharField(help_text="Immutable copy of the stock's trading code at capture time", max_length=32)),
                ('prediction_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_cutoff_date', models.DateField(db_index=True, help_text='Last trading session whose price data fed this prediction')),
                ('horizon_trading_days', models.PositiveSmallIntegerField()),
                ('target_date', models.DateField(blank=True, db_index=True, help_text='Trading session this prediction is settled against', null=True)),
                ('reference_close', models.FloatField(help_text='Close price at data_cutoff_date — the entry price for economic evaluation')),
                ('predicted_class', models.BooleanField(blank=True, help_text='True = forward return predicted positive', null=True)),
                ('predicted_probability', models.FloatField(blank=True, null=True)),
                ('rule_baseline_class', models.BooleanField(blank=True, help_text="predictor.predict_stock's rule-score sign", null=True)),
                ('naive_baseline_class', models.BooleanField(blank=True, help_text="Majority class observed in the model's own training data", null=True)),
                ('predicted_return', models.FloatField(blank=True, null=True)),
                ('predicted_price', models.FloatField(blank=True, null=True)),
                ('rule_baseline_return', models.FloatField(blank=True, help_text="Persistence baseline: prior session's 1-day return", null=True)),
                ('naive_baseline_return', models.FloatField(blank=True, help_text='Zero-return (no-change) baseline', null=True)),
                ('confidence_value', models.FloatField(blank=True, null=True)),
                ('confidence_label', models.CharField(blank=True, max_length=16)),
                ('data_quality_status', models.CharField(default='ok', help_text='ok / stale / thin_liquidity', max_length=16)),
                ('data_quality_notes', models.JSONField(blank=True, default=dict)),
                ('outcome_return', models.FloatField(blank=True, null=True)),
                ('outcome_class', models.BooleanField(blank=True, null=True)),
                ('outcome_price', models.FloatField(blank=True, null=True)),
                ('settlement_status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('excluded', 'Excluded')], db_index=True, default='pending', max_length=16)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('exclusion_reason', models.CharField(blank=True, max_length=64)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_snapshots', to='market.mlmodelversion')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_snapshots', to='market.stock')),
            ],
            options={
                'ordering': ['-prediction_at'],
                'indexes': [models.Index(fields=['model_family', 'exchange', 'settlement_status'], name='market_pred_model_f_b8a8b2_idx'), models.Index(fields=['model_family', 'exchange', 'horizon_trading_days', 'target_date'], name='market_pred_model_f_fef9a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_family', 'model_version_tag', 'stock_trading_code', 'exchange', 'data_cutoff_date', 'horizon_trading_days'), name='uniq_prediction_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='ReliabilityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('schema_version', models.CharField(default='1', max_length=16)),
                ('model_family', models.CharField(choices=[('forward_return_rf', 'Forward Return Classifier'), ('next_close_rf', 'Next Close Regressor')], db_index=True, max_length=32)),
                ('model_version_tag', models.CharField(blank=True, max_length=32)),
                ('exchange', models.CharField(choices=[('DSE', 'Dhaka Stock Exchange'), ('CSE', 'Chittagong Stock Exchange')], db_index=True, max_length=3)),
                ('horizon_trading_days', models.PositiveSmallIntegerField()),
                ('window_label', models.CharField(help_text='e.g. 30 / 90 / 180 / 365', max_length=16)),
                ('window_size', models.PositiveIntegerField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('insufficient_data', 'Insufficient data'), ('healthy', 'Healthy'), ('watch', 'Watch'), ('degraded', 'Degraded'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('confidence_intervals', models.JSONField(blank=True, default=dict)),
                ('drift', models.JSONField(blank=True, default=dict)),
                ('threshold_config', models.JSONField(blank=True, default=dict)),
                ('failure_detail', models.TextField(blank=True)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reliability_assessments', to='market.mlmodelversion')),
            ],
            options={
                'ordering': ['-run_at'],
                'indexes': [models.Index(fields=['model_family', 'exchange', 'horizon_trading_days', 'window_label', '-run_at'], name='market_reli_model_f_5fd51b_idx')],
            },
        ),
    ]
