# Generated by Django 6.0.7 on 2026-08-03 18:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_reliability_monitor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=64)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price_per_share', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fees', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('transaction_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='market.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_transactions', to='market.stock')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_portfolio_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='portfoliotransaction',
            index=models.Index(fields=['portfolio', 'stock'], name='market_port_portfol_76691f_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliotransaction',
            index=models.Index(fields=['portfolio', 'transaction_date'], name='market_port_portfol_c47301_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfoliotransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='portfolio_txn_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='portfoliotransaction',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_share__gte', 0)), name='portfolio_txn_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='portfoliotransaction',
            constraint=models.CheckConstraint(condition=models.Q(('fees__gte', 0)), name='portfolio_txn_fees_non_negative'),
        ),
    ]
