# Generated by Django 6.0.7 on 2026-08-05 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_portfolio_portfoliotransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='target_username_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('pipeline_triggered', 'Pipeline triggered'), ('model_activated', 'Model activated'), ('model_deactivated', 'Model deactivated'), ('account_created', 'Account created'), ('account_activated', 'Account activated'), ('account_deactivated', 'Account deactivated'), ('role_promoted', 'Role promoted'), ('role_demoted', 'Role demoted'), ('password_reset_initiated', 'Password reset initiated'), ('temp_password_assigned', 'Temporary password assigned'), ('first_login_password_changed', 'First-login password changed')], db_index=True, max_length=32),
        ),
    ]
