# Generated by Django 6.0.7 on 2026-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_adminauditlog_request_id_adminauditlog_target_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial success'), ('skipped', 'Skipped'), ('failure', 'Failure')], default='started', max_length=16),
        ),
    ]
