# Generated by Django 6.0.7 on 2026-08-06 17:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_adminauditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Admin autonomous paper fund', max_length=64, unique=True)),
                ('initial_cash', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=14)),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=14)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('strategy_config', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaperPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('opened_on', models.DateField(db_index=True)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('closed_on', models.DateField(blank=True, db_index=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('exit_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_entries', to='market.analysisresult')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_positions', to='market.stock')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='market.papertradingaccount')),
            ],
            options={
                'ordering': ['-opened_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaperEquitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('holdings_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_equity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('realized_pnl', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, max_digits=14)),
                ('open_positions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_snapshots', to='market.papertradingaccount')),
            ],
            options={
                'ordering': ['-as_of'],
            },
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('trade_date', models.DateField(db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('market_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('execution_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_effect', models.DecimalField(decimal_places=2, help_text='Negative for buys, positive for sells', max_digits=14)),
                ('reason', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market.paperposition')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_trades', to='market.analysisresult')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_trades', to='market.stock')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market.papertradingaccount')),
            ],
            options={
                'ordering': ['-trade_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('position', 'side'), name='one_paper_trade_per_position_side')],
            },
        ),
        migrations.AddConstraint(
            model_name='paperposition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('account', 'stock'), name='one_open_paper_position_per_stock'),
        ),
        migrations.AddConstraint(
            model_name='paperequitysnapshot',
            constraint=models.UniqueConstraint(fields=('account', 'as_of'), name='one_paper_equity_snapshot_per_day'),
        ),
    ]
