# Generated by Django 6.0.7 on 2026-08-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_papertradingaccount_paperposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperLearningFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_date', models.DateField(db_index=True)),
                ('outcome_date', models.DateField(db_index=True)),
                ('predicted_probability', models.FloatField(blank=True, null=True)),
                ('predicted_confidence', models.FloatField(blank=True, null=True)),
                ('predicted_score', models.FloatField(blank=True, null=True)),
                ('gross_return_pct', models.FloatField()),
                ('net_return_pct', models.FloatField()),
                ('profitable_after_costs', models.BooleanField(db_index=True)),
                ('holding_sessions', models.PositiveIntegerField()),
                ('exit_reason', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_feedback', to='market.paperposition')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_learning_feedback', to='market.stock')),
            ],
            options={
                'ordering': ['-outcome_date', '-id'],
            },
        ),
    ]
