# Generated by Django 6.0.7 on 2026-08-06 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_paperlearningfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperposition',
            name='maturity_date',
            field=models.DateField(blank=True, db_index=True, help_text='First session on which the virtual shares may be sold', null=True),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='settlement_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='PaperCashSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settlement_date', models.DateField(db_index=True)),
                ('is_settled', models.BooleanField(db_index=True, default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_settlements', to='market.papertradingaccount')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_settlement', to='market.papertrade')),
            ],
            options={
                'ordering': ['settlement_date', 'id'],
            },
        ),
    ]
