# Generated by Django 6.0.7 on 2026-08-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_paperposition_maturity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('unknown', 'Unknown (legacy / unspecified)'), ('dse_live', 'DSE live quote'), ('dse_history', 'DSE historical archive/bdshare'), ('dse_research_backfill', 'DSE external research backfill (CC BY 4.0)'), ('cse_live', 'CSE live quote'), ('cse_history', 'CSE historical bulk download'), ('cse_mirror_fallback', 'CSE mirrored from DSE (not real CSE data)'), ('synthetic_demo', 'Synthetic demo seed data'), ('synthetic_fallback', 'Synthetic fallback for a real code (fetch unavailable)')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='source',
            field=models.CharField(choices=[('unknown', 'Unknown (legacy / unspecified)'), ('dse_live', 'DSE live quote'), ('dse_history', 'DSE historical archive/bdshare'), ('dse_research_backfill', 'DSE external research backfill (CC BY 4.0)'), ('cse_live', 'CSE live quote'), ('cse_history', 'CSE historical bulk download'), ('cse_mirror_fallback', 'CSE mirrored from DSE (not real CSE data)'), ('synthetic_demo', 'Synthetic demo seed data'), ('synthetic_fallback', 'Synthetic fallback for a real code (fetch unavailable)')], db_index=True, default='unknown', max_length=32),
        ),
    ]
