# Generated by Django 6.0.7 on 2026-08-11
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("market", "0018_alter_importbatch_source_alter_pricehistory_source")]

    operations = [
        migrations.CreateModel(
            name="TaskHealth",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_name", models.CharField(max_length=128, unique=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("last_failure", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("current_health_status", models.CharField(choices=[("healthy", "Healthy"), ("unhealthy", "Unhealthy")], default="healthy", max_length=16)),
                ("last_error", models.TextField(blank=True)),
                ("run_duration_seconds", models.FloatField(blank=True, null=True)),
                ("symbols_attempted", models.PositiveIntegerField(default=0)),
                ("symbols_successful", models.PositiveIntegerField(default=0)),
                ("symbols_failed", models.PositiveIntegerField(default=0)),
                ("alert_state", models.CharField(choices=[("none", "No pending alert"), ("failure_pending", "Failure alert pending"), ("failure_sent", "Failure alert sent"), ("recovery_pending", "Recovery alert pending")], default="none", max_length=24)),
                ("last_alert", models.DateTimeField(blank=True, null=True)),
                ("last_recovery", models.DateTimeField(blank=True, null=True)),
            ],
        )
    ]
