# Generated by Django 6.0.7 on 2026-08-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_taskhealth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('pipeline_triggered', 'Pipeline triggered'), ('model_activated', 'Model activated'), ('model_deactivated', 'Model deactivated'), ('account_created', 'Account created'), ('account_activated', 'Account activated'), ('account_deactivated', 'Account deactivated'), ('account_deleted', 'Account deleted'), ('role_promoted', 'Role promoted'), ('role_demoted', 'Role demoted'), ('password_reset_initiated', 'Password reset initiated'), ('temp_password_assigned', 'Temporary password assigned'), ('first_login_password_changed', 'First-login password changed'), ('telegram_report_forced', 'Telegram ML report force-resent')], db_index=True, max_length=32),
        ),
    ]
