# Generated by Django 6.0.7 on 2026-08-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_alter_adminauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsnapshot',
            name='beta_90d',
            field=models.FloatField(blank=True, help_text='cov(stock, exchange index) / var(index) over the trailing 90 calendar days', null=True),
        ),
    ]
