# Generated by Django 6.0.7 on 2026-08-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0021_technicalsnapshot_beta_90d"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_value", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("max_single_position_pct", models.DecimalField(decimal_places=2, default=Decimal("35.00"), max_digits=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("portfolio", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="goal", to="market.portfolio")),
            ],
        ),
        migrations.CreateModel(
            name="ResearchNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=140)),
                ("body", models.TextField(max_length=4000)),
                ("target_price", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stock", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="research_notes", to="market.stock")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="research_notes", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"], "indexes": [models.Index(fields=["user", "stock", "-updated_at"], name="market_rese_user_id_d149ad_idx")]},
        ),
    ]
