# Generated by Django 6.0.7 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("market", "0022_portfoliogoal_researchnote")]

    operations = [
        migrations.AddField(
            model_name="portfoliotransaction",
            name="thesis",
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name="portfoliotransaction",
            name="target_price",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="portfoliotransaction",
            name="invalidation",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="portfoliotransaction",
            name="post_trade_review",
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
