# Generated by Django 6.0.7 on 2026-08-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_marketevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField(db_index=True)),
                ('period_label', models.CharField(blank=True, max_length=32)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('net_profit', models.FloatField(blank=True, null=True)),
                ('nav_per_share', models.FloatField(blank=True, null=True)),
                ('operating_cash_flow', models.FloatField(blank=True, null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('current_ratio', models.FloatField(blank=True, null=True)),
                ('dividend_per_share', models.FloatField(blank=True, null=True)),
                ('sponsor_pct', models.FloatField(blank=True, null=True)),
                ('institutional_pct', models.FloatField(blank=True, null=True)),
                ('foreign_pct', models.FloatField(blank=True, null=True)),
                ('auditor_qualification', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentals', to='market.stock')),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('stock', 'period_end')},
            },
        ),
    ]
