# Generated by Django 6.0.7 on 2026-08-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_fundamental_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField(db_index=True)),
                ('target_date', models.DateField(db_index=True)),
                ('last_close', models.FloatField()),
                ('predicted_close', models.FloatField()),
                ('predicted_return', models.FloatField()),
                ('candidate_name', models.CharField(default='shadow_analogue', max_length=64)),
                ('actual_close', models.FloatField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_forecasts', to='market.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['candidate_name', 'settled_at'], name='market_shad_candida_098a7a_idx')],
                'unique_together': {('stock', 'target_date', 'candidate_name')},
            },
        ),
    ]
