# Generated by Django 6.0.7 on 2026-08-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_shadow_forecasts'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketevent',
            name='event_time',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
