# Generated by Django 6.0.7 on 2026-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_marketevent_event_time_marketevent_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketevent',
            name='event_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
