# Generated by Django 6.0.7 on 2026-08-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_password_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
