# Generated by Django 6.0.7 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0003_userprofile_temp_password_expires_at")]

    operations = [migrations.AddField(model_name="userprofile", name="is_pending_approval", field=models.BooleanField(default=False))]
