# Generated by Django 6.0.7 on 2026-08-13

from django.db import migrations


def add_unique_email_index(apps, schema_editor):
    # Django's built-in auth_user.email isn't unique by default. A partial
    # index preserves existing legacy accounts with blank emails while
    # making every supplied address globally unique at the database layer.
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS accounts_unique_nonblank_email "
            "ON auth_user (email COLLATE NOCASE) WHERE email <> ''"
        )
    elif schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS accounts_unique_nonblank_email "
            "ON auth_user (LOWER(email)) WHERE email <> ''"
        )


def remove_unique_email_index(apps, schema_editor):
    schema_editor.execute("DROP INDEX IF EXISTS accounts_unique_nonblank_email")


class Migration(migrations.Migration):
    dependencies = [("accounts", "0005_userprofile_is_pending_approval")]

    operations = [migrations.RunPython(add_unique_email_index, remove_unique_email_index)]
