# Generated by Django 6.0.7 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0006_unique_nonblank_user_email")]

    operations = [migrations.AddField(model_name="userprofile", name="email_verified_at", field=models.DateTimeField(blank=True, null=True))]
