from django.urls import path

from market import views

urlpatterns = [
    path("market/", views.public_market_overview, name="public_market_overview"),
    path("events/", views.market_events, name="market_events"),
    path("documentation/", views.product_documentation, name="product_documentation"),
    path("legal/<slug:slug>/", views.legal_page, name="legal_page"),
    path("", views.home, name="home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("stocks/", views.stock_list, name="stock_list"),
    path("stocks/<str:exchange>/<str:code>/", views.stock_detail, name="stock_detail"),
    path("stocks/<str:exchange>/<str:code>/predict-price/", views.predict_price_view, name="predict_price"),
    path("stocks/<str:exchange>/<str:code>/watch/", views.toggle_watchlist, name="toggle_watchlist"),
    path("watchlist/", views.watchlist_view, name="watchlist"),
    path("compare/", views.compare_stocks, name="compare_stocks"),
    path("sectors/", views.sector_heatmap, name="sector_heatmap"),
    path("portfolio/", views.portfolio_redirect, name="portfolio_redirect"),
    path("portfolio/list/", views.portfolio_list, name="portfolio_list"),
    path("portfolio/create/", views.portfolio_create, name="portfolio_create"),
    path("portfolio/<int:portfolio_id>/", views.portfolio_detail, name="portfolio_detail"),
    path("portfolio/<int:portfolio_id>/rename/", views.portfolio_rename, name="portfolio_rename"),
    path("portfolio/<int:portfolio_id>/goal/", views.portfolio_goal_save, name="portfolio_goal_save"),
    path("portfolio/<int:portfolio_id>/export.csv", views.portfolio_export_csv, name="portfolio_export_csv"),
    path("portfolio/<int:portfolio_id>/import.csv", views.portfolio_import_csv, name="portfolio_import_csv"),
    path("portfolio/<int:portfolio_id>/set-default/", views.portfolio_set_default, name="portfolio_set_default"),
    path("portfolio/<int:portfolio_id>/delete/", views.portfolio_delete, name="portfolio_delete"),
    path("portfolio/<int:portfolio_id>/quotes.json", views.portfolio_quotes_json, name="portfolio_quotes_json"),
    path("portfolio/<int:portfolio_id>/transactions/", views.portfolio_transactions, name="portfolio_transactions"),
    path("portfolio/<int:portfolio_id>/transactions/add/", views.portfolio_add_transaction, name="portfolio_add_transaction"),
    path("portfolio/<int:portfolio_id>/holdings/add/", views.portfolio_add_holding, name="portfolio_add_holding"),
    path(
        "portfolio/<int:portfolio_id>/transactions/<int:txn_id>/edit/",
        views.portfolio_edit_transaction,
        name="portfolio_edit_transaction",
    ),
    path(
        "portfolio/<int:portfolio_id>/transactions/<int:txn_id>/delete/",
        views.portfolio_delete_transaction,
        name="portfolio_delete_transaction",
    ),
    path("backtests/", views.backtests_view, name="backtests"),
    path("alerts/", views.alerts_view, name="alerts"),
    path("alerts/rules/create/", views.alert_rule_create, name="alert_rule_create"),
    path("alerts/rules/<int:rule_id>/toggle/", views.alert_rule_toggle, name="alert_rule_toggle"),
    path("alerts/rules/<int:rule_id>/delete/", views.alert_rule_delete, name="alert_rule_delete"),
    path("stocks/<str:exchange>/<str:code>/notes/create/", views.research_note_create, name="research_note_create"),
    path("notes/<int:note_id>/delete/", views.research_note_delete, name="research_note_delete"),
    path("pipeline/", views.run_pipeline_view, name="run_pipeline"),
    path("pipeline/retry/<int:run_id>/", views.retry_task_view, name="retry_task"),
    path("telegram-report/preview/", views.telegram_report_preview, name="telegram_report_preview"),
    path("telegram-report/send/", views.telegram_report_send, name="telegram_report_send"),
    path("data-quality/", views.data_quality_view, name="data_quality"),
    path("ops/", views.ops_report_view, name="ops_report"),
    path("ml-reliability/", views.ml_reliability_view, name="ml_reliability"),
    path("paper-trading/", views.paper_trading_view, name="paper_trading"),
    path("paper-trading/control/", views.paper_trading_control, name="paper_trading_control"),
    path("tools/reminders/", views.admin_reminders_view, name="admin_reminders"),
    path("health/", views.health, name="health"),
    path("health/live/", views.liveness_view, name="health_live"),
    path("health/ready/", views.readiness_view, name="health_ready"),
    path("ticker.json", views.ticker_json, name="ticker_json"),
]
