# Generated by Django 6.0.7 on 2026-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlDailyReportDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('recipient_masked', models.CharField(max_length=32)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('retrying', 'Retrying'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('telegram_message_id', models.CharField(blank=True, max_length=32)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, help_text='Redacted — never contains the bot token.')),
                ('content_hash', models.CharField(blank=True, max_length=32)),
                ('model_version_summary', models.CharField(blank=True, max_length=255)),
                ('report_text', models.TextField(blank=True, help_text='The generated report, for preview/audit — sent or not.')),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-report_date', '-generated_at'],
            },
        ),
    ]
