# Generated by Django 6.0.7 on 2026-08-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0022_portfoliogoal_researchnote"),
        ("notifications", "0003_adminreminder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rule_type", models.CharField(choices=[("target_price", "Target price reached"), ("percent_move", "Percentage move"), ("signal_change", "BUY/SELL signal change"), ("confidence_change", "Prediction confidence reached")], max_length=24)),
                ("target_price", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("threshold_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("min_confidence", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("telegram_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_signal", models.CharField(blank=True, max_length=16)),
                ("last_confidence", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stock", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="alert_rules", to="market.stock")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="alert_rules", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(model_name="alert", name="rule", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deliveries", to="notifications.alertrule")),
        migrations.AddIndex(model_name="alertrule", index=models.Index(fields=["is_active", "rule_type"], name="notificatio_is_acti_2324ff_idx")),
        migrations.AddIndex(model_name="alertrule", index=models.Index(fields=["user", "stock"], name="notificatio_user_id_55ce30_idx")),
    ]
